name: Generate Metrics

on:
  schedule: [{cron: "0 12 * * *"}]

  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '.github/workflows/metrics.yml'
      
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: Metrics
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          config_display: large
          base: activity, community, metadata, repositories
          plugin_isocalendar: yes
          plugin_traffic: yes
